config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  resources :users, :only => [:new, :create, :edit, :update, :show]
  resources :fantasies
  resources :races

  get '/broadcast' => 'races#broadcast'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  mount ActionCable.server => '/cable'
end

app/models/race.rb
# == Schema Information
#
# Table name: races
#
#  id          :bigint(8)        not null, primary key
#  country     :text
#  flag        :text
#  track_map   :text
#  video       :text
#  fantasy_id  :integer
#  position_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Race < ApplicationRecord
  has_and_belongs_to_many :fantasies
  has_one :position
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :check_for_login

  def show
    @race = Race.find params[:id]
    @fantasy_teams = Fantasy.all.filter { |f| f.user_id == @current_user.id }
  end

  def broadcast
    message = Message.create :content => 'new message'
    ActionCable.server.broadcast 'race_channel', flag: rander_flag(flag)
    render :plain => 'race flag'
  end

  def edit
    @race = Race.find_by :country => "Australia"
    $driver_positions = Position.last.driver_ids.map { |d| d }.shuffle
    @fantasy_team = Fantasy.all.filter { |f| f.user_id == @current_user.id }.first
  end

  def update
    if $driver_positions.present? then
      Race.find(params[:id]).fantasy_ids.each do |f_id|
        points_per_position = [25, 18, 15, 12, 10, 8, 6, 4, 2, 1]
        fantasy_team = Fantasy.find f_id
        driver_ids = fantasy_team.driver_ids
        constructor_driver_ids = Constructor.find(fantasy_team.constructor_id).driver_ids
        all_driver_ids = driver_ids + constructor_driver_ids

        @position_arr = all_driver_ids.map do |driver_id|
          @pos_arr = $driver_positions.map.with_index do |d_id, i|
            i if d_id == driver_id
          end
          @pos_arr = @pos_arr.filter { |i| i.present? }
        end
        @position_arr = @position_arr.reduce { |acc, val| acc + val }

        @points_arr = @position_arr.map do |position|
          @pts_arr = points_per_position.map.with_index do |pos, i|
            pos if i == position
          end
          @pts_arr = @pts_arr.filter { |i| i.present? }
        end
        @points_arr = @points_arr.reduce { |acc, val| acc + val }
        @points_arr = @points_arr.reduce { |acc, val| acc + val }.to_i

        fantasy_team.points = @points_arr
        fantasy_team.save
      end
    end

    race = Race.find params[:id]
    race.update race_params
    redirect_to edit_race_path(race)
  end

  def index
    @races = Race.all
  end

  private
  def race_params
    params.require(:race).permit(:flag, :fantasy_ids => [])
  end

  def render_flag(flag)
    ApplicationController.renderer.render(partial: 'races/flag', locals: { flag: flag })
  end
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/races/edit.html.erb
<h1><%= @race.country %> &nbsp;:: &nbsp; <span class="timer"></span></h1>

<div class="race-edit-container">
  <div class="race-edit-container-menu">
    <div class="race-edit-container-menu-teams">
      <h3>Fantasy Teams</h3>
      <% @race.fantasy_ids.each do |id| %>
        <p>
          <strong><%= Fantasy.find(id).name %>:</strong>
          <%= Fantasy.find(id).points %> points
        </p>
      <% end %>
    </div>

    <div class="race-edit-container-menu-positions">
      <h3>Positions</h3>
      <% $driver_positions.each_with_index do |d_id, i| %>
        <p><strong><%= (i + 1).ordinalize %>:</strong> <%= Driver.find(d_id).name %></p>
      <% end %>

      <%= form_for @race do |f| %>
        <%= f.hidden_field :flag %>
        <%= f.submit "End Race"%>
      <% end %>
    </div>
  </div>

  <div class="race-edit-container-track">
    <div class="codepen-border"></div>
    <p class="codepen" data-height="601" data-theme-id="light" data-default-tab="result" data-user="chrislaneau" data-slug-hash="jRQwgG" style="height: 601px; box-sizing: border-box; display: flex; align-items: center; justify-content: center; margin: 1em 0; padding: 1em;" data-pen-title="jRQwgG">
    </p>
    <script async src="https://static.codepen.io/assets/embed/ei.js"></script></div>
  </div>
</div>

app/views/races/index.html.erb
<h1>2019 F1 Races</h1>

<% @races.each do |r| %>
  <%= link_to r.country, race_path(r), :class => "race-select" %>
<% end %>

app/views/races/show.html.erb
<h1><%= @race.country %></h1>

<div class="team-select-container">
  <h3>Choose your fantasy team </h3>
  <%= form_for @race do |f| %>
    <%= f.collection_radio_buttons(:fantasy_ids, @fantasy_teams, :id, :name) do |c| %>
      <%= c.label(class:"team-select-container-label") { c.radio_button + c.text } %>
    <% end %>
    <%= f.submit "Start Race", :class => "team-select-container-btn" %>
  <% end %>
</div>