config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  resources :users, :only => [:new, :create, :edit, :update, :show]
  resources :fantasies
  resources :races

  get '/broadcast' => 'races#broadcast'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  mount ActionCable.server => '/cable'
end

app/models/fantasy.rb
# == Schema Information
#
# Table name: fantasies
#
#  id             :bigint(8)        not null, primary key
#  name           :text
#  image          :text
#  budget         :float
#  points         :integer
#  user_id        :integer
#  driver_id      :integer
#  constructor_id :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Fantasy < ApplicationRecord
  has_and_belongs_to_many :drivers
  has_and_belongs_to_many :races
  has_one :constructor
  belongs_to :user, :optional => true
end

app/controllers/fantasies_controller.rb
class FantasiesController < ApplicationController
  before_action :check_for_login, :only => [:new, :create, :show]

  def new
    @fantasy_team = Fantasy.new
  end

  def create
    fantasy_team = Fantasy.create fantasy_params
    @current_user.fantasies << fantasy_team
    redirect_to fantasies_path
  end

  def edit
    @fantasy_team = Fantasy.find params[:id]
    @drivers = Driver.all
    @constructors = Constructor.all
  end

  def update
    fantasy_team = Fantasy.find params[:id]
    fantasy_team.update fantasy_params

    team_values = fantasy_team.driver_ids.map { |d_id|
      Driver.find(d_id).value
    }.reduce { |acc, val| acc + val }.round(1) + Constructor.find(
      fantasy_team.constructor_id
    ).value.round(1)

    # if team_values < 100.0 then
      fantasy_team.budget = 100.0 - team_values
      fantasy_team.save
      redirect_to fantasies_path
    # end
  end

  def index
    @fantasy_teams = Fantasy.all
  end

  def show
    id = @current_user.id
    f_ids = User.find_by(:id => id).fantasy_ids
    @fantasy_teams = Fantasy.find (f_ids)
  end

  private
  def fantasy_params
    params.require(:fantasy).permit(:name, :image, :budget, :points, :user_id, :constructor_id, :driver_ids => [])
  end
end

app/helpers/fantasies_helper.rb
module FantasiesHelper
end

app/views/fantasies/_form.html.erb
<%= form_for @fantasy_team do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, :autofocus => true, :required => true %>

  <%= f.label :image, "Photo" %>
  <%= f.text_field :image, :placeholder => "http://..." %>

  <%= f.label :constructor_id, "Choose 1 Constructor", :class => "create-fantasy-team-label-constructor" %>
  <%= f.collection_radio_buttons(:constructor_id, Constructor.all, :id, :name) do |c| %>
    <%= c.label(class:"display-block create-fantasy-team-label create-fantasy-team-label-radio") { c.radio_button + c.text } %>
  <% end %>

  <%= f.label :driver_ids, "Choose 5 Drivers", :class => "create-fantasy-team-label-drivers" %>
  <%= f.collection_check_boxes(:driver_ids, Driver.all, :id, :name) do |d| %>
    <%= d.label(class:"display-block create-fantasy-team-label create-fantasy-team-label-check") { d.check_box + d.text } %>
  <% end %>

  <%= f.submit "Save Team" %>
  <%= link_to "Cancel", fantasies_path %>

<% end %>

app/views/fantasies/edit.html.erb
<h1>Edit Fantasy Team <%= @team_values %></h1>

<div class="create-fantasy-team">

  <%= render :partial => "form" %>
</div>

app/views/fantasies/index.html.erb
<h1>Fantasy Teams</h1>

<div class="fantasy-teams-container">
  <% @fantasy_teams.each do |team| %>
    <% if team.user_id == @current_user.id %>
      <div class="fantasy-teams-container-team">
        <%= link_to team.name, edit_fantasy_path(team.id), :class => "fantasy-teams-container-team-name" %>
        <% team.driver_ids.each do |d_id| %>
          <%= link_to Driver.find(d_id).name, edit_fantasy_path(team.id), :class => "fantasy-teams-container-team-driver" %>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <%= link_to "Create New Fantasy Team", new_fantasy_path, :class => "fantasy-teams-container-team fantasy-teams-container-team-new" %>
</div>

app/views/fantasies/new.html.erb
<h1>Create Fantasy Team</h1>

<div class="create-fantasy-team">
  <h3 class="create-fantasy-team-budget">Budget: $<%= @fantasy_team.budget %>m</h3>

  <%= render :partial => "form" %>
</div>

app/views/fantasies/show.html.erb
<% @fantasy_teams.each do |team| %>
  <h1>Name: <%= team.name %></h1>
  <% team.driver_ids.each do |driver_id| %>
  <ul>
    <li><%= Driver.find(driver_id).name %></li>
  </ul>
  <% end %>
<% end %>