config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  resources :users, :only => [:new, :create, :edit, :update, :show]
  resources :fantasies
  resources :races

  get '/broadcast' => 'races#broadcast'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/constructor.rb
# == Schema Information
#
# Table name: constructors
#
#  id         :bigint(8)        not null, primary key
#  name       :text
#  logo       :text
#  car_image  :text
#  value      :float
#  driver_id  :integer
#  fantasy_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Constructor < ApplicationRecord
  has_many :drivers
  has_and_belongs_to_many :fantasies, :optional => true
end

app/models/driver.rb
# == Schema Information
#
# Table name: drivers
#
#  id             :bigint(8)        not null, primary key
#  name           :text
#  nationality    :text
#  image          :text
#  value          :float
#  constructor_id :integer
#  fantasy_id     :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Driver < ApplicationRecord
  belongs_to :constructor, :optional => true
  has_and_belongs_to_many :fantasies
  has_and_belongs_to_many :positions, through: :races
end

app/models/fantasy.rb
# == Schema Information
#
# Table name: fantasies
#
#  id             :bigint(8)        not null, primary key
#  name           :text
#  image          :text
#  budget         :float
#  points         :integer
#  user_id        :integer
#  driver_id      :integer
#  constructor_id :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Fantasy < ApplicationRecord
  has_and_belongs_to_many :drivers
  has_and_belongs_to_many :races
  has_one :constructor
  belongs_to :user, :optional => true
end

app/models/position.rb
# == Schema Information
#
# Table name: positions
#
#  id         :bigint(8)        not null, primary key
#  _1         :text
#  _2         :text
#  _3         :text
#  _4         :text
#  _5         :text
#  _6         :text
#  _7         :text
#  _8         :text
#  _9         :text
#  _10        :text
#  _11        :text
#  _12        :text
#  _13        :text
#  _14        :text
#  _15        :text
#  _16        :text
#  _17        :text
#  _18        :text
#  _19        :text
#  _20        :text
#  race_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Position < ApplicationRecord
  has_and_belongs_to_many :drivers, through: :races
  has_and_belongs_to_many :races
end

app/models/race.rb
# == Schema Information
#
# Table name: races
#
#  id          :bigint(8)        not null, primary key
#  country     :text
#  flag        :text
#  track_map   :text
#  video       :text
#  fantasy_id  :integer
#  position_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Race < ApplicationRecord
  has_and_belongs_to_many :fantasies
  has_one :position
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :text
#  name            :text
#  password_digest :text
#  image           :text
#  fantasy_id      :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  has_secure_password
  has_many :fantasies
  validates :email, :presence => true, :uniqueness => true
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  def new
  end

  def update
    driver = Fantasy.find params[:id]
    driver.update driver_params
    redirect_to fantasy_path(driver.id)
  end

  private
  def driver_params
    params.require(:driver).permit(:fantasy_ids => [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :check_for_login

  def show
    @race = Race.find params[:id]
    @fantasy_teams = Fantasy.all.filter { |f| f.user_id == @current_user.id }
  end

  def broadcast
    message = Message.create :content => 'new message'
    ActionCable.server.broadcast 'race_channel', flag: rander_flag(flag)
    render :plain => 'race flag'
  end

  def edit
    @race = Race.find_by :country => "Australia"
    $driver_positions = Position.last.driver_ids.map { |d| d }.shuffle
    @fantasy_team = Fantasy.all.filter { |f| f.user_id == @current_user.id }.first
  end

  def update
    if $driver_positions.present? then
      Race.find(params[:id]).fantasy_ids.each do |f_id|
        points_per_position = [25, 18, 15, 12, 10, 8, 6, 4, 2, 1]
        fantasy_team = Fantasy.find f_id
        driver_ids = fantasy_team.driver_ids
        constructor_driver_ids = Constructor.find(fantasy_team.constructor_id).driver_ids
        all_driver_ids = driver_ids + constructor_driver_ids

        @position_arr = all_driver_ids.map do |driver_id|
          @pos_arr = $driver_positions.map.with_index do |d_id, i|
            i if d_id == driver_id
          end
          @pos_arr = @pos_arr.filter { |i| i.present? }
        end
        @position_arr = @position_arr.reduce { |acc, val| acc + val }

        @points_arr = @position_arr.map do |position|
          @pts_arr = points_per_position.map.with_index do |pos, i|
            pos if i == position
          end
          @pts_arr = @pts_arr.filter { |i| i.present? }
        end
        @points_arr = @points_arr.reduce { |acc, val| acc + val }
        @points_arr = @points_arr.reduce { |acc, val| acc + val }.to_i

        fantasy_team.points = @points_arr
        fantasy_team.save
      end
    end

    race = Race.find params[:id]
    race.update race_params
    redirect_to edit_race_path(race)
  end

  def index
    @races = Race.all
  end

  private
  def race_params
    params.require(:race).permit(:flag, :fantasy_ids => [])
  end

  def render_flag(flag)
    ApplicationController.renderer.render(partial: 'races/flag', locals: { flag: flag })
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.find @current_user.id
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    # @user = User.find @current_user.id
  end

  def edit
    @user = User.find @current_user.id
  end

  def update
    user = User.find @current_user.id
    user.update user_params
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :name, :image, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/constructors_helper.rb
module ConstructorsHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/fantasies_helper.rb
module FantasiesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">
  </head>

  <body>
    <nav>
      <div class="logo">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 411.99 48"><defs><style>.cls-1{fill:#fff;}</style></defs><title>Asset 1</title><g id="Layer_2" data-name="Layer 2"><g id="F1_Fantasy" data-name="F1 Fantasy"><path class="cls-1" d="M130.17,35.76h1.58V40h.88V35.76h1.59V35h-4.05ZM134.78,40h.84V36.14h0L137,40h.72l1.38-3.86h0V40H140V35h-1.22l-1.34,3.92h0L136,35h-1.23Z"/><path class="cls-1" d="M40.37,22.79,22.63,40H0L28.15,12.06C38.62,1.7,43.67,0,61.51,0H132l-15.3,15H63.53C50.2,15,47.36,16,40.37,22.79Zm74.05-5.42H63.85c-13.43,0-15.53,1-21.62,7.12L26.72,40h21l5-5c3.29-3.3,4.77-3.62,11.42-3.62H100.4ZM119.89,40,160,0H135.09l-40,40Z"/><path class="cls-1" d="M170,0h31.52V8.8H180.67v7.36h20.85V25H180.67V40H170Z"/><path class="cls-1" d="M236.56,40H214.64c-6.45,0-9.92-3-9.92-7.52,0-5,3.84-7.31,8.54-10.51l9.06-6.24H205.47V8h14c12.26,0,17.06,5.39,17.06,14.67ZM227,32.27V21.65l-9.65,7.52c-1.23,1-1.65,1.18-1.65,1.92s.53,1.18,1.86,1.18Z"/><path class="cls-1" d="M242.22,8h19.84c9.39,0,13.28,5,13.28,13.07V40H265.21V20.8c0-3.31-.86-4.53-4-4.53h-8.86V40H242.22Z"/><path class="cls-1" d="M279,8h5.17V1.49h9.34V8h17.33v7.73H293.48v13c0,2.72,1.06,3.58,3.62,3.58h5.18V40h-6.35c-8.85,0-12.32-3.63-12.32-11.31v-13H279Z"/><path class="cls-1" d="M338.12,40H316.2c-6.45,0-9.92-3-9.92-7.52,0-5,3.84-7.31,8.53-10.51l9.07-6.24H307V8h14c12.27,0,17.07,5.39,17.07,14.67Zm-9.6-7.73V21.65l-9.65,7.52c-1.23,1-1.66,1.18-1.66,1.92s.54,1.18,1.87,1.18Z"/><path class="cls-1" d="M352.68,27.09c-6.45-1.28-9.86-4.42-9.86-9.76,0-5,3.73-9.33,12.48-9.33h15.89v7.73H354.5c-2.14,0-2.67.75-2.67,1.55s.53,1.49,2.13,1.81l7.9,1.55c7.89,1.55,10.93,4.48,10.93,9.65,0,5.76-4.27,9.71-13.23,9.71H343.88V32.27h17.39c2.29,0,2.72-.7,2.72-1.71s-1.07-1.44-2.61-1.76Z"/><path class="cls-1" d="M394,28.11c.42,0,.74-.16,1-1L401.22,8H412L400.53,39c-1.92,5.23-6.35,9-14.08,9H377.7V39.52h9.65c2.56,0,3.68-1.07,4.59-3.79l.37-1.06h-2.56a5.63,5.63,0,0,1-5.81-3.9L374.66,8h11.15l7,19.15C393.11,28,393.59,28.11,394,28.11Z"/></g></g></svg>
      </div>
      <% if @current_user.present? %>
        <%= link_to "Fantasy Teams", fantasies_path %>
        <%= link_to "Races", races_path %>
        <%= link_to "My Profile", edit_user_path(@current_user) %>
        <%= link_to "Sign Out #{ @current_user.name }", login_path, :method => "delete" %>
      <% else %>
        <%= link_to "Home", root_path %>
        <%= link_to "Sign Up", new_user_path %>
        <%= link_to "Log In", login_path %>
      <% end %>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<% if @current_user.present? %>
  <h1>Welcome <%= @current_user.name %></h1>

  <div class="home">
    <%= link_to "Create a Team", new_fantasy_path, :class => "hero-cta" %>
  </div>
<% else %>
  <h1>2019 Season Now Live</h1>
  <div class="hero">
    <%= link_to "Sign Up Right Now", new_user_path, :class => "hero-cta" %>
  </div>
<% end %>